name: Publish + build
on:
  push:
    branches: [ '**' ]
    paths-ignore: [ '**.md' ]
  workflow_call:
    secrets:
      MAVEN_USERNAME:
        required: false
      MAVEN_PASSWORD:
        required: false
      ORG_GRADLE_PROJECT_mavenCentralPassword:
        required: false
      ORG_GRADLE_PROJECT_mavenCentralUsername:
        required: false
      ORG_GRADLE_PROJECT_signingInMemoryKey:
        required: false
      ORG_GRADLE_PROJECT_signingInMemoryKeyPassword:
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MAVEN_USERNAME: ${{ vars.MAVEN_USERNAME }}
      MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
      ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.ORG_GRADLE_PROJECT_MAVENCENTRALPASSWORD }}
      ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.ORG_GRADLE_PROJECT_MAVENCENTRALUSERNAME }}
      ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEY }}
      ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEYPASSWORD }}
    steps:
      -   name: Checkout
          uses: actions/checkout@v3
          with:
            fetch-depth: 0

      -   name: Setup Java
          uses: actions/setup-java@v3
          with:
            distribution: zulu
            java-version: 17
            cache: gradle

      -   name: Setup Gradle
          uses: gradle/gradle-build-action@v2

      -   name: Build and Publish
          run: ./gradlew build publish --no-daemon -x test

      -   name: Upload Artifacts
          uses: actions/upload-artifact@v3
          with:
            name: Lavalink-Client.zip
            path: |
              build/libs/lavalink-client-*.jar
