name: Docs Push

on:
    release:
        types: [ published ]
    workflow_dispatch: {}

concurrency:
    group: pages-${{ github.ref }}
    cancel-in-progress: true

jobs:
    deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            deployments: write
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - uses: actions/setup-java@v4
              with:
                  java-version: 17
                  distribution: zulu
                  cache: gradle
            -   name: Build docs
                run: ./gradlew --no-daemon dokkaHtml dokkaJavadoc
            - name: Copy javadoc subfolder
              run: mv build/dokka/javadoc build/dokka/html/
            - uses: actions/upload-pages-artifact@v1
              with:
                  path: 'build/dokka/html'
            - uses: cloudflare/pages-action@v1
              with:
                  apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  projectName: ${{ vars.CLOUDFLARE_PROJECT_NAME }}
                  directory: build/dokka/html
                  gitHubToken: ${{ secrets.GITHUB_TOKEN }}
                  wranglerVersion: '3'
