name: Publish package

on:
  push:
    branches: [ main ]
  workflow_dispatch:  {}

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
        with:
          path: './'
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: zulu
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew --no-daemon publish -x test
        env:
          USERNAME: ${{ secrets.M2_USER }}
          PASSWORD: ${{ secrets.M2_PASS }}
          SNAPSHOT: true
