name: Release

on:
  release:
    types: [ published ]

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets:
      ORG_GRADLE_PROJECT_MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
      ORG_GRADLE_PROJECT_MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
      ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
      ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
      ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_IN_MEMORY_KEY }}
      ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_IN_MEMORY_KEY_PASSWORD }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      -   name: Checkout
          uses: actions/checkout@v4

      -   name: Download Artifacts
          uses: actions/download-artifact@v4
          with:
            name: Lavalink-Client.zip

      -   name: Upload Artifacts to GitHub Release
          uses: ncipollo/release-action@v1
          with:
            artifacts: |
              lavalink-client*.jar
            allowUpdates: true
            omitBodyDuringUpdate: true
            omitDraftDuringUpdate: true
            omitNameDuringUpdate: true
            omitPrereleaseDuringUpdate: true
